Implemented a skeleton code for csr matrix class
bkochuna/ners570f20-Lab06 pull request #51
Opened 2020-10-19 10:19 UTC by hpleei

1. Wrote a class skeleton for the CSR matrix
2. Defined methods/interfaces for the class: Constructor, print, getter
3. No destructor as it wouldn't need any dynamically allocated data structure for this object.
4. Using vector instead of plain array for more flexibilities and simplicity.

2020-10-19 15:00 UTC, bkochuna commented
@hpleei this is going to have to wait because the implementation of the `SparseMatrix` class which this needs to extend is not yet completed (#47). I did this last night, and need to clean up the keeps before I push it out. This will happen today.

2020-10-22 15:43 UTC, knbarton requested changes
Thanks for getting this started! I'd like to look through the code more in depth later today, but for now I have some suggestions for spelling changes.

2020-10-22 15:43 UTC, knbarton commented on src/csr/csrsparsemat.hpp
> +tempalte <typename T>
```suggestion
template <typename T>
```

2020-10-22 15:43 UTC, knbarton commented on src/csr/csrsparsemat.hpp
> +class CrsSparseMatrix{
```suggestion
class CsrSparseMatrix{
```

2020-10-22 15:43 UTC, knbarton commented on src/csr/csrsparsemat.hpp
> +        vector<vector<T>> crs_matrix;
Spelling
```suggestion
        vector<vector<T>> csr_matrix;
```

2020-10-22 15:43 UTC, knbarton commented on src/csr/csrsparsemat.hpp
> +        CrsSparseMatrix(const vector<T> & element_vec, const vector<int> & col_vec, const vector<int> & rowp_vec);
```suggestion
        CsrSparseMatrix(const vector<T> & element_vec, const vector<int> & col_vec, const vector<int> & rowp_vec);
```

2020-10-22 15:43 UTC, knbarton commented on src/csr/csrsparsemat.hpp
> +        vector<vector<T>> get_crs_matrix();
```suggestion
        vector<vector<T>> get_csr_matrix();
```

2020-10-24 03:03 UTC, knbarton commented
I went ahead and made some changes to make the class so that it follows the testSparseMatrix class. I also added a csrTest to the test file to make sure the skeleton code works.

2020-10-24 03:49 UTC, knbarton commented
This pull request now encompasses issue #19 as well, so I added the other assignee for that issue as a reviewer to look at the cmake files.

2020-10-24 22:23 UTC, littlewatkins reviewed
This all looks great to me! I don't have a good enough C++ background to speak to the specific code itself, but the content overall, like the header files and especially the test, is really nice. I give my approval, but I will wait for others thoughts.

2020-10-26 19:17 UTC, bkochuna approved these changes
If its good for @knbarton its good for me.

2020-10-26 19:19 UTC, Qicang approved these changes
It looks good to me to merge this branch.

2020-10-26 19:29 UTC, merged