Implemented skeleton code for csc class
bkochuna/ners570f20-Lab06 pull request #52
Opened 2020-10-19 10:52 UTC by hpleei

1. Wrote a class skeleton for the CSC matrix
2. Defined methods/interfaces for the class: Constructor, print, getter
3. No destructor as it wouldn't need any dynamically allocated data structure for this object.
4. Using vector instead of plain array for more flexibilities and simplicity.

2020-10-21 05:10 UTC, Qicang requested changes
Very nice work. But the class need to be modified to be the derived type of the base class ```SparseMatrix```

2020-10-21 05:10 UTC, Qicang commented on src/csc/cscsparsemat.hpp
> +    public:
The class should be the derived type of the Sparse matrix. Just the same as what Prof Kochunas @bkochuna  commented in #50. 
```
class CscSparseMatrix : public SparseMatrix 
```

2020-10-21 13:55 UTC, hpleei commented on src/csc/cscsparsemat.hpp
> +    public:
Got it. I just noticed that we are using some inheritance in this assignment. As professor's comment in #51 says, we would wait till his base class implementation gets done. And maybe @preethammohan9  can hop in working on that and I can help clarifying c++ inheritance concepts if he needs help.

2020-10-26 19:18 UTC, bkochuna approved these changes
Deferring to the review by @preethammohan9

2020-10-26 19:25 UTC, Qicang commented
The checks are failed. Should fix this before merging into master @hpleei

2020-10-27 03:57 UTC, hpleei commented
Found out that works after me has some problems and faced conflicts but finally fixed all of them and pushed. Was able to pass Travis CI -branch and Travis CI- Pull Request testing but don't know why both "c-i/travis-ci/pr" and "c-i/travis-ci/push" tests are pending and never gets tested (it keep saying it's being queued but it never goes to next step)

2020-10-27 04:09 UTC, preethammohan9 commented
I added back the csc subdirectory and tests to the build system and the tests again failed. Do we know what is going on?

2020-10-27 15:34 UTC, Qicang approved these changes

2020-10-27 16:06 UTC, Qicang commented
@preethammohan9 All the checks passed, once you review all the changes, you can merge the code.

2020-10-27 18:47 UTC, preethammohan9 reviewed
As I myself edited a few files, I am happy it works now. Minor typo in test/cscTest.cpp line 6 "scopint" -> "scoping". Typo in comments in lines 15-16 of src/cscsparsemat.hpp. These have no consequence. Other than that, we have all the methods that are pure virtual in the parent class defined here. My one question @hpleei, @deanrp2 is, wouldn't we need the elements array, row idx array and col pointer array as attributes of the class, since we will be implementing the void assembleStorage() to "assemble" the matrix in some way using _buildCoeff?

2020-10-27 19:01 UTC, preethammohan9 approved these changes
We can defer the question in the review above to the implementation team, and any changes can be made in the future. In the interest of time, I am going to go ahead and merge this with main.

2020-10-27 19:01 UTC, merged

2020-10-27 19:04 UTC, preethammohan9 commented
Oops, I actually did a merge commit instead of a "Squash and Merge". Sincere apologies!!! :/