Update CMakeLists.txt
bkochuna/ners570f20-Lab06 pull request #61
Opened 2020-10-28 04:09 UTC by noeyjd

@yucanding @Qicang Defined a default set of compiler flags for release, debug, and all builds. Although I am not sure if this is accurate, please review my work accordingly.

2020-10-28 15:53 UTC, yucanding reviewed
Checks have failed so the current codes contain errors.

2020-10-28 15:53 UTC, yucanding commented on CMakeLists.txt
> +
I think maybe we can set the default one (Release for example) in this way:
```suggestion
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release")
endif()
```

2020-10-28 17:50 UTC, Qicang commented
The checks are not passed. Be sure to check why the checks failed. @noeyjd @yucanding When you change the CMakeLists, you should test it locally to see whether you can compile the code.

2020-10-28 17:58 UTC, Qicang requested changes

2020-10-28 17:58 UTC, Qicang commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS         "${CMAKE_CXX_FLAGS} -Wall"
missing )

2020-10-28 17:58 UTC, Qicang commented on CMakeLists.txt
> +$ make VERBOSE=1
What is the purpose of these two commands?

2020-10-28 19:26 UTC, Qicang requested changes

2020-10-28 19:42 UTC, Qicang requested changes

2020-10-28 19:42 UTC, Qicang commented on CMakeLists.txt
> +  )
Get rid of it

2020-10-29 22:13 UTC, yucanding commented
Update CMakeLists.txt

2020-10-29 22:13 UTC, merged