WIP:Adding COO Sparse Matrix Class to build system #27
bkochuna/ners570f20-Lab06 pull request #62
Opened 2020-10-28 15:48 UTC by peihsun570

Description: adding the COO sparse matrix class to the CMakelists.txt file so that when the project is configured and built. This associated source and test file are compiled.

Definition of Done: The source and header file compile.

2020-10-28 16:24 UTC, peareric requested changes

2020-10-28 16:24 UTC, peareric commented on issue27/CMakeLists.txt
> +set(COOsource COOsparsemat.cpp)
After .cpp is implemented we should add the line
```
add_library(coo ${SOURCES})
```
and move this file to the src/coo directory.

2020-10-28 16:41 UTC, mhig-umich commented on issue27/CMakeLists.txt
> +set(COOsource COOsparsemat.cpp)
Eric's change looks good. My only question is the COOsource going to be different because CSC and CSR use SOURCES?
`set(SOURCES csrsparsemat.cpp)`
`set(SOURCES cscsparsemat.cpp)`

2020-10-28 16:46 UTC, peareric commented on issue27/CMakeLists.txt
> +set(COOsource COOsparsemat.cpp)
Correct, we can also change COOsource to SOURCES in the set(...) and add_library(...) commands for consistency if desired.

2020-10-28 16:49 UTC, peihsun570 commented on issue27/CMakeLists.txt
> +set(COOsource COOsparsemat.cpp)
Modified as reviewed

2020-10-28 16:52 UTC, peareric commented
Looks good, after Coosparsemat.cpp is implemented and merged into main, we can pull main into this branch, make sure everything builds, merge this PR, close issue #27.

2020-10-28 20:09 UTC, bkochuna commented on src/coo/CMakeLists.txt
> +set(COOsource COOsparsemat.cpp)
So this will work, but this is not really the best way to implement this...

By doing it this way, the library is now compiling a different library file for each matrix type. Instead, what we want is a single library (SpMV) with all matrix types.

So what you need to figure out how to do is how to add this source file to the list of source files processed to create the SpMV library.

This is defined in [src/CMakeLists.txt](https://github.com/bkochuna/ners570f20-Lab06/blob/main/src/CMakeLists.txt)
So be thinking about how you can _append_ `COOsparsemat.cpp` to the `SOURCES` CMake variable **in this file**.

2020-10-29 01:28 UTC, bkochuna commented on src/coo/CMakeLists.txt
> +add_library(coo ${SOURCES})
Same comment as before... 

> So this will work, but this is not really the best way to implement this...
> 
> By doing it this way, the library is now compiling a different library file for each matrix type. Instead, what we want is a single library (SpMV) with all matrix types.
> 
> So what you need to figure out how to do is how to add this source file to the list of source files processed to create the SpMV library.
> 
> This is defined in src/CMakeLists.txt
> So be thinking about how you can append COOsparsemat.cpp to the SOURCES CMake variable in this file.

2020-10-29 02:28 UTC, peihsun570 reviewed
The source file to the list of source file processed to create the SpMV library commit below

2020-10-29 02:31 UTC, peihsun570 commented on src/coo/CMakeLists.txt
> +add_library(coo ${SOURCES})
Would it be adding the subdirectory of coo on the src/CMakeLists.txt?

add_subdirectory(csr)
add_subdirectory(csc)
add_subdirectory(coo)

add_library(SpMV ${SOURCES} )

2020-10-29 02:48 UTC, bkochuna commented on src/coo/CMakeLists.txt
> +add_library(coo ${SOURCES})
That is part of it. Think of SOURCES like a global variable that persists through each add_subdirectory call. Each of these calls should be modifying the value of SOURCES. You can use the MESSAGE function in CMake to print the value.

2020-10-29 15:25 UTC, peihsun570 commented
@peareric @mhig-umich @bkochuna could you review it, please

2020-10-29 15:27 UTC, peareric commented
I actually don't like the need for relative paths in the source files - I'll fix it a sec

2020-10-29 15:32 UTC, peareric commented
@peihsun570 how does this look?

2020-10-29 15:33 UTC, peareric approved these changes

2020-10-29 15:54 UTC, merged